[project]
name = "universal-translator"
version = "0.1.0"

dependencies = [
    "requests",
    "websockets",
    "pyaudio",
    "torch",
    "numpy",
    "silero-vad",
    "edge-tts",
    "pydub>=0.25.1",
    "uvicorn",
    "fastapi",
    "jinja2",
    "itsdangerous",
    "python-multipart",
    "toml>=0.10.2",
]
